### ISSUE TITLE
REST API Authentication without using Login form authentication 

### ISSUE THREAD

**Issue by harikant-lftt** [sweid4keycloak/bankid4keycloak#43]
Currently we have to show  KC login form to start the authentication process.

Is there any way to to use As REST API for Authentication.

In my Case we have Mobile app and APP team does not want to open web view in mobile app, they are interested to use some api endpoint to login.

Like we do for Direct Grant  using above URL {{kc_url}}/realms/{{realm}}/protocol/openid-connect/token

**Comment by harikant-lftt** [comment]
Hi @ullgren, @isrjo 

Is there any possibility to enhance this to support direct grant or I'm completely missing point here

**Comment by ullgren** [comment]
@harikant-lftt interesting use case. Have not payed it enough thought right now to say if it is a good idea or not. We also would have to implement it so that it is implemented in a way that follows the bankid guidelines. 

But it is technically possible  to expose an api endpoint that provides something like the direct grant flow.

I'll put this on my mental roadmap and contributions are always welcome.
