### ISSUE TITLE
Support for KC >= 21

### ISSUE THREAD

**Issue by bjornuppeke** [sweid4keycloak/bankid4keycloak#51]
How far away are you from supporting KC >= 21? I saw your comments in [this KC issue](https://github.com/keycloak/keycloak/issues/15344#issuecomment-1611562883) and without knowing that much about the situation it seems there might be a solution on the horizon?

Considering the newly released [security vulnerability](https://securityblog.omegapoint.se/en/writeup-keycloak-cve-2023-6027/) I am hoping to be able to upgrade KC in the near future while still using this BankID provider.

Thanks!

**Comment by mikaelkaron** [comment]
Since [this discussion](https://github.com/keycloak/keycloak/discussions/25862) is now closed with “fixed in KC 24” maybe what’s needed is in place again?

**Comment by ullgren** [comment]
We still have this issue in KC 22+
https://github.com/keycloak/keycloak/issues/21891

It is a minor issue that we could document away.

The problem is that two fields, client id and secret, is always added to the provider configuration screen. These are marked as mandatory by keycloak. However since it is not used in the BankID provider they make no sense in our case.

We could cut a KC 24 release and add to the documentation that you just have to add some value into these fields.

**Comment by mikaelkaron** [comment]
That would be nice to have until KC core implements a permanent method to remove/hide/disable these fields.

**Comment by ullgren** [comment]
Closing this as duplicate of https://github.com/sweid4keycloak/bankid4keycloak/pull/38
