### ISSUE TITLE
Collect call must have a check that should linked with current user session

### ISSUE THREAD

**Issue by harikant-lftt** [sweid4keycloak/bankid4keycloak#52]
**Describe the bug**
There is slight possibility user A can get control of user B.  if user A  get hold of bankidRef(the value use in collect call) of User B and replace his  bankidRef value with user B in collect call and somehow user B dely his BankId approval.
 1) User A  and User B both start the Authentication Process
2) User A Take BankidRef Of B, and replace it with his own bankidRef value (this can be done using some http interceptor tools)
3) User B delay his Bankid approval and User A approve first 
4) User A will have session of User B
**Expected behavior**

User A should not able to gain access of User B

**Screenshots**
NA
**Environment:**

Any Env

**Additional context**

In Collect call we should add a check bankidRef must belong to current user session

**Comment by CazeW** [comment]
Unless you can prove this vulnerability, I don't think it's viable in reality. Just because you have the other users orderRef, all you can do with that is to do a collect to get the status of the identification session. You cannot identify yourself as the other person. The only window you have to exploit this is to time your collect call in between when User B authenticates themselves and before their session does a collect call.

BankID also stores the user IP from where the authentication was started, but I'm not sure if it uses that value to check from where the collect call comes from. If they do check that, then this becomes even harder to exploit.

**Comment by harikant-lftt** [comment]
I was also in the same understanding as you, and I could not agree with my Security review team but our Security review team was able to  demo this, they were using some interceptor.

 I agree there is very minimum  window for this but it can be exploited. I had live demo with our securty review team.

I don't have all the tool with me to demo this.

**Comment by ullgren** [comment]
@harikant-lftt Thanks for the report.
I would be interested in hearing the details or even seeing the demo.
Was the interceptor a man in the middle attack compromising the TLS connection between the client and keycloak ?
Or was this something else ?

**Comment by ullgren** [comment]
@harikant-lftt I will go a head and close this issue. 
From my understanding, from the information you shared, the demo used a interceptor, capturing the traffic using some type of man in the middle style attack. 
If this is true the users session will also be subject to being hijacked, so linking the collect call to it will, as far as I see, not solve the problem anyway.

I'm happy to look into this again if/when you can provide more details. If you or the security team does not want to reveal details in public you can contact me directly.
